---
title: "Regional Shiny App Data Prep"
author: "Tina Cheng, Nat Goodby, & Kathy Gerst"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(shiny)
library(leaflet)
library(nabatr)
library(sf)
library(RColorBrewer)
library(here)
```

```{r NABat API}

# ENTER NABat USERNAME / PASSWORD

username = 'ngoodby@batcon.org'
password = 'HiaqfH*S6481'

token = get_nabat_gql_token(username, password)
token = get_refresh_token(token)
project_df = get_projects(token)
token = get_refresh_token(token)

# ENTER PROJECT ID; Can use project_df to look up number.

# project_id = unique(project_df$project_id)

project_id = c(963, #Bishop BLM
               936, #BLM California Desert Conservation Area
               353, #California NABat Project
               1062, #CDFW Long-term Acoustic Monitoring Project
               1067, #Desert National Wildlife Refuge Acoustic Monitoring
               857, #Elko BLM Biodiversity Program
               508, #Forest Service Region 5
               812, #Hungry Valley SVRA Bat Program
               222, #Marin Bat Monitoring
               885, #NDOW NABat in Nevada
               # 1085, #Northwest Nevada Incidental Bat Acoustic Sampling: 2021
               401, #NPS Klamath region NABat cells
               343, #NPS Mojave Desert Network Bat Monitoring
               223, #Pinnacles Bat monitoring
               909, #Pyramid Lake Paiute Tribe
               386#, #San Luis National Wildlife Refuge Complex Bat Survey
               # 957, #SoCal Bat Working Group Volunteer Monitoring
               # 947, #USFWS Inland SoCal Monitoring
               # 911, #Yurok Tribe Bat Inventory and Monitoring Project
  
)

sa_survey_df = get_sa_project_summary(token,
                                      project_df,
                                      project_id[1])

additional_projects <- project_id[-1]

if (length(additional_projects > 0)){
  for (i in additional_projects){
  sa_survey_df_add = get_sa_project_summary(token,
                                      project_df,
                                      i)
  sa_survey_df <- bind_rows(sa_survey_df, sa_survey_df_add)
}
}

token = get_refresh_token(token)
sa_bulk_df = get_sa_bulk_wavs(token,
                              sa_survey_df,
                              year = 'all')

token = get_refresh_token(token)
species_df = get_species(token = token)

#joining data
all_dat <- left_join(sa_bulk_df, species_df, by = c("manual_id" = "id"))

all_dat$survey_event_id <- as.numeric(all_dat$survey_event_id)
sa_survey_df$survey_event_id <- as.numeric(sa_survey_df$survey_event_id)

all_dat <- left_join(all_dat, sa_survey_df, keep = FALSE)
```

```{r Data Prep}
species_ref <- read_csv(here::here("data", "species_reference_table.csv"))

names_to_filter <- c("Q10k", "Q15k", "Q20k", "Q25k", "Q40k", "Q50k","LoF","HiF", "Noise", "MY40", "Social", "25k", "40k", "HighF", "LowF", "40kMyo", "NoID", "MYSP")

dat_spp <- all_dat %>% 
  separate_rows(species_code) %>% 
  dplyr::filter(!species_code %in% names_to_filter) %>% 
  dplyr::filter(nchar(species_code) == 4) %>% # filter to 4 letter species codes.
  dplyr::filter(!is.na(manual_id)) %>% 
  dplyr::filter(!is.na(species_code)) %>% 
  mutate(year = lubridate::year(recording_night)) %>%
  left_join(., species_ref, by = c("species_code" = "species_code")) %>% 
  mutate(species_code = ifelse(is.na(species_full_name), species_code, species_full_name))

sites <- all_dat %>%
  dplyr::distinct(grts_cell_id, location_name, latitude, longitude) %>%
  dplyr::group_by(grts_cell_id, location_name) %>%
  dplyr::summarise(latitude = mean(latitude),
                   longitude = mean(longitude)) %>%
  dplyr::mutate(country = "US")

load(paste0(here::here(), "/data/grts.grid.rda"))

grts_usa <- grts.grid %>% filter(country == "US")

species_grts <- left_join(dat_spp, sites) %>% 
  distinct(grts_cell_id, species_code, year, .keep_all = TRUE) %>% 
  left_join(grts_usa, by = c("grts_cell_id" = "GRTS_ID"))
```

```{r}
write_csv(species_grts, paste0(here::here(), "/data/species_grts.csv"))
```

```{r}
#Prepping iucn spatial layer for mapping species' ranges

#read in iucn shapefile
iucn_shp <- st_read(here::here("data", "TERRESTRIAL_MAMMALS"), "TERRESTRIAL_MAMMALS")

#myso only - overlap iucn range with hiber range
iucn_chiroptera <- iucn_shp %>% 
  st_as_sf(crs = 4326) %>% 
  dplyr::filter(`order_` == "CHIROPTERA") %>% 
  dplyr::select(binomial, geometry) %>% 
  mutate(species_code = toupper(map_chr(str_extract_all(binomial, '\\b(\\w)[A-z]'), paste, collapse = ""))) %>% 
  left_join(species_ref, by = c("species_code" = "species_code"))  %>%
  mutate(species_code = species_full_name)
  

st_write(iucn_chiroptera, here::here("data", "iucn_chiroptera/iucn_chiroptera.shp"), append = FALSE)
```
